[default.general]
chip = "RP2040"

[default.rtt]
# Whether or not an RTTUI should be opened after flashing.
enabled = true
# A list of channel associations to be displayed. If left empty, all channels are displayed.
# formats are: String, Defmt, BinaryLE,
channels = [
    # { up = 0, down = 0, name = "name", format = "String" },
#    { up = 0, down = 0, name = "Terminal", format = "String" },
#    { up = 2, down = 2, name = "Data", format = "String" },

    # How to enable Defmt formatting (https://github.com/knurling-rs/defmt)
    # (formats on host, not on microcontroller)?
    # microcontroller setup: https://github.com/knurling-rs/app-template
    # { up = 0, name = "defmt_name", format = "Defmt" },
]
# The duration in ms for which the logger should retry to attach to RTT.
timeout = 3000
# Whether timestamps in the RTTUI are enabled
show_timestamps = false
# Whether to save rtt history buffer on exit.
log_enabled = true
# Where to save rtt history buffer relative to manifest path.
log_path = "./logs"
